version: "3.3"
services:
  web:
    build: .
    ports:
      - "80:8765"
    environment:
      FLASK_ENV: dev
      PORT: 8765
      # DATABASE_URL: postgres://test-url
      SLACK_MESSAGE_WEBHOOK: https://hooks.slack.com/services/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
