"""empty message

Revision ID: 33b9cd170bcf
Revises: ca3c75df524f
Create Date: 2021-01-28 16:59:58.926869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b9cd170bcf'
down_revision = 'ca3c75df524f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labware',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('labware', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labware')
    # ### end Alembic commands ###
