"""empty message

Revision ID: 692400f22001
Revises: 
Create Date: 2021-01-05 14:00:01.441348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692400f22001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocol',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('protocol', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protocol')
    # ### end Alembic commands ###
