"""empty message

Revision ID: 7438840162fd
Revises: 9d9241c05845
Create Date: 2021-01-18 15:53:18.776052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7438840162fd'
down_revision = '9d9241c05845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_webhook',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slack_webhook', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_webhook')
    # ### end Alembic commands ###
