"""empty message

Revision ID: 9d9241c05845
Revises: 692400f22001
Create Date: 2021-01-09 16:20:12.845396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9241c05845'
down_revision = '692400f22001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labware',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('labware', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipette',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipette', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipette')
    op.drop_table('labware')
    # ### end Alembic commands ###
